apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-automation
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - kubectl get deploy
          restartPolicy: OnFailure
