apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-green
spec:
    selector:
        matchLabels:
            app: nginx-green
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx-green
        spec:
            containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-green
spec:
    type: NodePort
    selector:
        app: nginx-green
    ports:
        - port: 80
          targetPort: 80
