name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job1: 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install minikube
        uses: medyagh/setup-minikube@master
        
      - name: create deployment
        run: kubectl apply -f deploy-to-minikube.yml

      # Runs a set of commands using the runners shell
      - name: Get deployment
        run: kubectl get deploy
